name: 'Code Scanner'
description: 'Scan codebase for existence scan keyword'
inputs:
  scan-keyword:
    description: 'Keyword to search in codebase'
    required: false
    default: 'console.log'
  codebase-path:
    description: 'Path to search for codebase'
    required: false
    default: '.'
  extension-filter:
    description: 'Filter extension for files'
    required: false
    default: '.js'
  fail-build:
    description: 'Option to fail build if keyword exists'
    required: false
    default: 'true'
outputs:
  results:
    description: 'The list of scan-keyword input in codebase'
runs:
  using: 'node12'
  main: 'index.js'